### ISSUE TITLE
Add ability to add return codes from a configuration

### ISSUE THREAD

**Issue by nsoblath** [driplineorg/dripline-cpp#40]
Standard top-level item in the config.

```
return-codes:
  - my_code_1:
      value: 1120
      description: A very important error
  - my_code_2:
      value: 1121
      description: A useless error
````

or 

```
return-codes: /path/to/file/with/return_codes.yaml
```
